[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
tower = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# config
config = "0.14.1"
dotenv = "0.15.0"
chrono = "0.4.38"

jsonwebtoken = "9.0"
bb8 = "0.9.0"
bb8-redis = "0.21.0"